#!/usr/bin/env python3
"""Work out whether the Lekwena radar is running, and record it for the site.

The site cannot tell from the browser: the radar image is served over plain
http (blocked outright on the https site) and its scan time is burnt into the
GIF as pixels. The data server does, however, send an honest Last-Modified
header on that GIF, which moves every few minutes while the radar scans and
stops dead when it does not. That header is the whole signal.

Writes _data/radar_status.yml, which every radar mention on the site reads.
The file is rewritten only when the status flips, plus a keepalive at most
once every KEEPALIVE_DAYS - see the note on that constant.

Standard library only; the workflow installs nothing.
"""

import email.utils
import os
import re
import sys
import urllib.error
import urllib.request
from datetime import datetime, timedelta, timezone

CONFIG = "_config.yml"
TARGET = os.path.join("_data", "radar_status.yml")

# Hysteresis. A scan younger than ONLINE_WITHIN means the radar is running; one
# older than OFFLINE_AFTER means it is not. In between, keep whatever was
# recorded last, so one late upload does not flip the site offline and back.
ONLINE_WITHIN = timedelta(minutes=30)
OFFLINE_AFTER = timedelta(hours=2)

# GitHub disables scheduled workflows in a public repository after 60 days
# without a commit. The radar can easily be off for longer than that, and the
# whole point of this job is to notice when it comes back - so it refreshes
# the file, and with it the repository, at least this often.
KEEPALIVE_DAYS = 30

TIMEOUT = 30

# A Last-Modified this far ahead of GitHub's clock is a wrong server clock or a
# malformed header, not a radar scanning from the future. Treat it as a failed
# observation rather than as proof the radar is online.
FUTURE_TOLERANCE = timedelta(minutes=10)


def config_value(text, key):
    """Read one simple top-level-or-nested `key: "value"` scalar. Enough for
    the two lines needed here, without pulling in a YAML parser."""
    m = re.search(r'^\s*%s:\s*"?([^"\n#]+?)"?\s*(?:#.*)?$' % re.escape(key), text, re.M)
    if not m:
        sys.exit("could not find %r in %s" % (key, CONFIG))
    return m.group(1).strip()


def read_recorded():
    try:
        with open(TARGET, encoding="utf-8") as fh:
            text = fh.read()
    except OSError:
        return {}
    out = {}
    for key in ("status", "last_scan", "recorded"):
        m = re.search(r'^%s:\s*"?([^"\n]*)"?\s*$' % key, text, re.M)
        if m:
            out[key] = m.group(1).strip()
    return out


def parse_iso(value):
    try:
        return datetime.strptime(value, "%Y-%m-%dT%H:%M:%SZ").replace(tzinfo=timezone.utc)
    except (TypeError, ValueError):
        return None


def iso(dt):
    return dt.strftime("%Y-%m-%dT%H:%M:%SZ")


def write(status, last_scan, now):
    with open(TARGET, "w", encoding="utf-8") as fh:
        fh.write(
            "# GENERATED by .github/workflows/radar-status.yml - do not edit by hand.\n"
            "#\n"
            "# Derived from the Last-Modified header of the radar image on the data\n"
            "# server. To force a status regardless of this file, set radar.status in\n"
            "# _config.yml.\n"
            "status: %s\n"
            "last_scan: \"%s\"\n"
            "recorded: \"%s\"\n" % (status, last_scan, iso(now))
        )


def fail(message, before, now):
    """A failed observation says nothing about the radar, so the recorded state
    is left alone - except that the monthly heartbeat still runs. Otherwise a
    long outage of the data server, as seen from GitHub, would let the schedule
    lapse and the site would never notice the radar's return. Exits non-zero
    either way, so the run shows as failed."""
    recorded = parse_iso(before.get("recorded"))
    if before.get("status") and (recorded is None or
                                 now - recorded > timedelta(days=KEEPALIVE_DAYS)):
        write(before["status"], before.get("last_scan", ""), now)
        print("heartbeat: refreshed %s despite the failure" % TARGET)
    sys.exit(message)


def main():
    with open(CONFIG, encoding="utf-8") as fh:
        cfg = fh.read()
    url = config_value(cfg, "data_host").rstrip("/") + config_value(cfg, "radar_gif")

    now = datetime.now(timezone.utc)
    before = read_recorded()

    req = urllib.request.Request(url, method="HEAD",
                                 headers={"User-Agent": "lekwenaradar.co.za radar status"})
    try:
        with urllib.request.urlopen(req, timeout=TIMEOUT) as resp:
            modified = resp.headers.get("Last-Modified")
    except (urllib.error.URLError, OSError) as exc:
        # Not being able to reach the server from GitHub says nothing about
        # the radar.
        fail("could not reach %s: %s" % (url, exc), before, now)

    if not modified:
        fail("%s sent no Last-Modified header" % url, before, now)
    try:
        parsed = email.utils.parsedate_to_datetime(modified)
    except (TypeError, ValueError):
        parsed = None
    if parsed is None or parsed.tzinfo is None:
        fail("unparseable Last-Modified header: %r" % modified, before, now)
    last_scan = parsed.astimezone(timezone.utc)
    if last_scan > now + FUTURE_TOLERANCE:
        fail("Last-Modified %s is in the future" % iso(last_scan), before, now)

    age = now - last_scan

    if age <= ONLINE_WITHIN:
        status = "online"
    elif age > OFFLINE_AFTER:
        status = "offline"
    else:
        status = before.get("status") or "offline"

    recorded = parse_iso(before.get("recorded"))
    changed = status != before.get("status")
    stale = recorded is None or now - recorded > timedelta(days=KEEPALIVE_DAYS)
    # While offline the banner shows the date of the last scan, so a scan that
    # happened unobserved - the radar ran briefly between two checks that both
    # saw it offline - must still move that date. Online, the scan time changes
    # every few minutes and is not shown, so it is not chased.
    rescanned = status == "offline" and iso(last_scan) != before.get("last_scan")

    print("last scan %s (%s ago) -> %s" % (iso(last_scan), str(age).split(".")[0], status))
    if not (changed or stale or rescanned):
        print("unchanged since %s; leaving %s alone" % (before.get("recorded"), TARGET))
        return 0

    write(status, iso(last_scan), now)
    reason = "status changed" if changed else ("new scan while offline" if rescanned else "keepalive")
    print("wrote %s (%s)" % (TARGET, reason))
    return 0


if __name__ == "__main__":
    sys.exit(main())
